name: allfit_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.5
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  kpostal: ^0.5.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  lint: ^1.8.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
