name: Build iOS

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.4.0

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate Build Runner Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS App
        run: flutter build ios --no-codesign

      - name: Convert to IPA
        run: |
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip Payload.ipa
          rm -Rf Payload

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v.3.1.0
        with:
          name: ios-release
          path: Payload.ipa

      - name: Delete Build File
        run: rm Payload.ipa
